# Generated by Django 3.1.3 on 2020-12-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0002_auto_20201201_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
