# Generated by Django 3.1.3 on 2020-11-16 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0002_auto_20201113_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(default=None, srid=4326),
        ),
    ]
