# Generated by Django 3.1.3 on 2021-01-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0003_commune_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCoeurVille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_acv', models.CharField(max_length=6)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindivisions.commune')),
            ],
        ),
    ]
