# Generated by Django 3.1.3 on 2020-11-16 10:51

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0003_auto_20201116_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, srid=4326),
        ),
    ]
