# Generated by Django 3.1.3 on 2020-11-16 11:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0005_auto_20201116_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codeinsee', models.CharField(max_length=3)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindivisions.region')),
            ],
        ),
    ]
