# Generated by Django 3.1.3 on 2021-01-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0005_zoneemploi'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='zone_emploi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.zoneemploi'),
        ),
    ]
