# Generated by Django 3.1.3 on 2021-01-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0006_commune_zone_emploi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadrage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, null=True)),
                ('population', models.IntegerField()),
                ('births', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('livingstandard', models.IntegerField()),
            ],
        ),
    ]
