# Generated by Django 3.1.3 on 2020-11-16 13:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0006_departement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codeinsee', models.CharField(max_length=5)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindivisions.departement')),
            ],
        ),
    ]
