# Generated by Django 3.1.3 on 2020-11-16 15:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0007_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
