# Generated by Django 3.1.3 on 2021-01-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0007_cadrage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrage',
            name='commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.commune'),
        ),
    ]
