# Generated by Django 3.1.3 on 2021-01-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0009_auto_20210113_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrage',
            name='surface',
            field=models.IntegerField(null=True),
        ),
    ]
