# Generated by Django 3.1.3 on 2021-01-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0010_cadrage_surface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actioncoeurville',
            name='commune',
        ),
        migrations.AddField(
            model_name='commune',
            name='acv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.actioncoeurville'),
        ),
    ]
