# Generated by Django 3.1.3 on 2021-01-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0011_auto_20210115_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrage',
            name='less25',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cadrage',
            name='plus65',
            field=models.IntegerField(null=True),
        ),
    ]
