# Generated by Django 3.1.3 on 2020-11-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0011_auto_20201118_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epci',
            name='codeinsee',
            field=models.CharField(max_length=9),
        ),
    ]
