# Generated by Django 3.1.3 on 2021-01-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0012_auto_20210120_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadrage',
            name='births',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cadrage',
            name='deaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cadrage',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
