# Generated by Django 3.1.3 on 2020-11-18 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0013_auto_20201118_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epci',
            old_name='siren',
            new_name='codesiren',
        ),
    ]
