# Generated by Django 3.1.3 on 2021-01-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0014_cadrage_youthindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrage',
            name='evolution',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cadrage',
            name='soldeapparent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='cadrage',
            name='soldenaturel',
            field=models.FloatField(null=True),
        ),
    ]
