# Generated by Django 3.1.3 on 2021-01-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0015_auto_20210121_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrage',
            name='density',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cadrage',
            name='surface',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cadrage',
            name='youthindex',
            field=models.FloatField(null=True),
        ),
    ]
