# Generated by Django 3.1.3 on 2021-01-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0016_auto_20210129_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrage',
            name='typologie_evol',
            field=models.IntegerField(null=True),
        ),
    ]
