# Generated by Django 3.1.3 on 2021-03-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0018_entreprises_communes_entreprises_departements_entreprises_regions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entreprises_departements',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='entreprises_regions',
            name='commune',
        ),
        migrations.AddField(
            model_name='entreprises_departements',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.departement'),
        ),
        migrations.AddField(
            model_name='entreprises_regions',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.region'),
        ),
    ]
