# Generated by Django 3.1.3 on 2021-03-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0019_auto_20210303_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprises_communes',
            name='effectifs_culture',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entreprises_communes',
            name='effectifs_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entreprises_departements',
            name='effectifs_culture',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entreprises_departements',
            name='effectifs_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entreprises_regions',
            name='effectifs_culture',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entreprises_regions',
            name='effectifs_total',
            field=models.IntegerField(null=True),
        ),
    ]
