# Generated by Django 3.1.3 on 2021-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0021_auto_20210308_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypologieEvolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('typologie', models.CharField(max_length=200)),
            ],
        ),
    ]
