# Generated by Django 3.1.3 on 2021-03-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0023_domaine_secteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepensesRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depenses_fonctionnement', models.FloatField(null=True)),
                ('depenses_investissement', models.FloatField(null=True)),
                ('depenses_totales', models.FloatField(null=True)),
                ('secteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.secteur')),
            ],
        ),
    ]
