# Generated by Django 3.1.3 on 2021-03-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0024_depensesregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensesregion',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.region'),
        ),
    ]
