# Generated by Django 3.1.3 on 2021-03-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0025_depensesregion_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensesregion',
            name='annee',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
