# Generated by Django 3.1.3 on 2021-04-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0026_depensesregion_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='AireAttractionVille',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commune_AAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.BooleanField(null=True)),
                ('tranche_population', models.IntegerField(null=True)),
                ('AAV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindivisions.aireattractionville')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindivisions.commune')),
            ],
        ),
        migrations.AddField(
            model_name='aireattractionville',
            name='commune',
            field=models.ManyToManyField(through='admindivisions.Commune_AAV', to='admindivisions.Commune'),
        ),
    ]
