# Generated by Django 3.1.3 on 2021-04-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0028_auto_20210412_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune_aav',
            name='tranche_population',
        ),
        migrations.AddField(
            model_name='aireattractionville',
            name='codeinsee',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='aireattractionville',
            name='tranche_population',
            field=models.IntegerField(null=True),
        ),
    ]
