# Generated by Django 3.1.3 on 2021-04-13 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0029_auto_20210413_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aireattractionville',
            name='commune',
        ),
    ]
