# Generated by Django 3.1.3 on 2021-04-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0030_remove_aireattractionville_commune'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoneemploi',
            name='annee',
            field=models.CharField(default=2020, max_length=4),
            preserve_default=False,
        ),
    ]
