# Generated by Django 3.1.3 on 2021-04-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0031_zoneemploi_annee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi_ZE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actifs', models.IntegerField(null=True)),
                ('nombre_profession_culturelle', models.IntegerField(null=True)),
                ('nombre_secteur_culturel', models.IntegerField(null=True)),
                ('zone_emploi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.zoneemploi')),
            ],
        ),
    ]
