# Generated by Django 3.1.3 on 2021-04-26 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0032_emploi_ze'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi_Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actifs', models.IntegerField(null=True)),
                ('nombre_profession_culturelle', models.IntegerField(null=True)),
                ('nombre_secteur_culturel', models.IntegerField(null=True)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.departement')),
            ],
        ),
    ]
