# Generated by Django 3.1.3 on 2021-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0035_depensescommunes'),
    ]

    operations = [
        migrations.AddField(
            model_name='epci',
            name='annee',
            field=models.CharField(default=2020, max_length=4),
            preserve_default=False,
        ),
    ]
