# Generated by Django 3.1.3 on 2021-05-17 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0037_depensesepci'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depensesepci',
            old_name='departement',
            new_name='epci',
        ),
    ]
