# Generated by Django 3.1.3 on 2021-05-19 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0038_auto_20210517_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emploi_Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actifs', models.IntegerField(null=True)),
                ('nombre_profession_culturelle', models.IntegerField(null=True)),
                ('nombre_secteur_culturel', models.IntegerField(null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.region')),
            ],
        ),
    ]
