# Generated by Django 3.1.3 on 2021-05-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0039_emploi_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensescommunes',
            name='population',
            field=models.IntegerField(null=True),
        ),
    ]
