# Generated by Django 3.1.3 on 2021-05-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0041_auto_20210520_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='depensesepci',
            name='population',
            field=models.FloatField(null=True),
        ),
    ]
