# Generated by Django 3.1.3 on 2021-06-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0042_depensesepci_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepensesMinistereRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depenses_fonctionnement', models.FloatField(null=True)),
                ('depenses_investissement', models.FloatField(null=True)),
                ('depenses_totales', models.FloatField(null=True)),
                ('annee', models.CharField(max_length=4, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.region')),
            ],
        ),
        migrations.CreateModel(
            name='DepensesMinistereDepartement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depenses_fonctionnement', models.FloatField(null=True)),
                ('depenses_investissement', models.FloatField(null=True)),
                ('depenses_totales', models.FloatField(null=True)),
                ('annee', models.CharField(max_length=4, null=True)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.departement')),
            ],
        ),
    ]
