# Generated by Django 3.1.3 on 2021-06-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0043_depensesministeredepartement_depensesministereregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadrage',
            name='tauxpauvrete',
            field=models.FloatField(null=True),
        ),
    ]
