# Generated by Django 3.1.3 on 2021-07-02 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0044_cadrage_tauxpauvrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprises_communes',
            name='annee',
            field=models.CharField(default='2017', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='entreprises_communes',
            name='date_ajout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
