# Generated by Django 3.1.3 on 2021-07-13 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0045_auto_20210702_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=1000)),
                ('millesime', models.CharField(max_length=4)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.source')),
            ],
        ),
    ]
