# Generated by Django 3.1.3 on 2021-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0046_source_variable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
