# Generated by Django 3.1.3 on 2021-08-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0047_auto_20210713_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
