# Generated by Django 3.1.3 on 2021-08-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0048_region_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='image',
            field=models.ImageField(null=True, upload_to='portraits/'),
        ),
    ]
