# Generated by Django 3.1.3 on 2021-08-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0049_auto_20210809_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='standard_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
