# Generated by Django 3.1.3 on 2021-08-19 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0050_region_standard_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variable',
            old_name='millesime',
            new_name='year',
        ),
    ]
