# Generated by Django 3.1.3 on 2021-08-19 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0051_auto_20210819_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.source'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
