# Generated by Django 3.1.3 on 2021-08-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0052_auto_20210819_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='image_line',
            field=models.ImageField(null=True, upload_to='portraits/'),
        ),
    ]
