# Generated by Django 3.1.3 on 2021-08-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0053_region_image_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='image_line',
            new_name='image_carte',
        ),
    ]
