# Generated by Django 3.1.3 on 2021-08-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0054_auto_20210831_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='image',
            new_name='image_portrait',
        ),
    ]
