# Generated by Django 3.1.3 on 2021-10-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0056_auto_20210831_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ('nom',)},
        ),
        migrations.AddField(
            model_name='variable',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
