# Generated by Django 3.1.3 on 2021-10-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0057_auto_20211007_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variable',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='variable',
            name='file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
