# Generated by Django 3.2.9 on 2021-12-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0060_complementaryressource_variables'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetitesVillesDeDemain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_pvd', models.CharField(max_length=6)),
            ],
        ),
    ]
