# Generated by Django 3.2.9 on 2021-12-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0061_petitesvillesdedemain'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='pvd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.petitesvillesdedemain'),
        ),
    ]
