# Generated by Django 3.2.9 on 2021-12-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0063_alter_petitesvillesdedemain_code_pvd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petitesvillesdedemain',
            name='code_pvd',
            field=models.CharField(max_length=20),
        ),
    ]
