# Generated by Django 3.1.3 on 2020-11-28 00:56

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admindivisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typology', models.CharField(max_length=2, null=True)),
                ('surface', models.IntegerField(null=True)),
                ('surface_network', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_type', models.CharField(max_length=10, null=True)),
                ('number_chairs', models.IntegerField(null=True)),
                ('number_rooms', models.IntegerField(null=True)),
                ('rooms_3d', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline_Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_DEPS', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Monument_Historique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_DEPS', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300, null=True)),
                ('formatted_address', models.CharField(max_length=300, null=True)),
                ('complement_address', models.CharField(max_length=300, null=True)),
                ('postal_code', models.CharField(max_length=20, null=True)),
                ('codeinsee', models.CharField(max_length=300, null=True)),
                ('codeinsee_arrondt', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=300, null=True)),
                ('id_origin', models.CharField(max_length=20, null=True)),
                ('gps', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('bibliotheque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.bibliotheque')),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.cinema')),
                ('commune', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindivisions.commune')),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.discipline_equipement')),
                ('equipement_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.equipement_type')),
                ('labels', models.ManyToManyField(to='equipements.Label')),
                ('mh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.monument_historique')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.source')),
            ],
        ),
    ]
