# Generated by Django 3.1.3 on 2021-01-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0013_auto_20210120_1636'),
        ('equipements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement_Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindivisions.commune')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.equipement')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='commune_secondaire',
            field=models.ManyToManyField(related_name='communes_secondaires', through='equipements.Equipement_Commune', to='admindivisions.Commune'),
        ),
    ]
