# Generated by Django 3.1.3 on 2021-01-20 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0003_auto_20210120_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='domaine',
        ),
        migrations.CreateModel(
            name='Equipement_Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.domaine')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.equipement')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='domaine',
            field=models.ManyToManyField(through='equipements.Equipement_Domaine', to='equipements.Domaine'),
        ),
    ]
