# Generated by Django 3.1.3 on 2021-01-20 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0005_auto_20210120_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='sous_domaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_domaine', to='equipements.domaine'),
        ),
    ]
