# Generated by Django 3.1.3 on 2021-01-20 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0008_auto_20210120_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.CharField(max_length=2, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='architecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.architecture'),
        ),
    ]
