# Generated by Django 3.1.3 on 2021-01-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0009_auto_20210120_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='codeinsee',
        ),
        migrations.AddField(
            model_name='bibliotheque',
            name='code_bib',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bibliotheque',
            name='code_ua',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
