# Generated by Django 3.1.3 on 2021-02-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0010_auto_20210120_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='formatted_address',
        ),
    ]
