# Generated by Django 3.1.3 on 2021-02-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0011_remove_equipement_formatted_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='postal_code',
        ),
    ]
