# Generated by Django 3.1.3 on 2021-02-01 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0012_remove_equipement_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='commune_secondaire',
            new_name='communes_secondaire',
        ),
    ]
