# Generated by Django 3.1.3 on 2021-02-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0013_auto_20210201_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='year',
            new_name='label_year',
        ),
    ]
