# Generated by Django 3.1.3 on 2021-02-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0014_auto_20210201_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecture',
            name='precision',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
