# Generated by Django 3.1.3 on 2021-02-01 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0015_auto_20210201_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monument_historique',
            old_name='owner',
            new_name='proprietaire',
        ),
    ]
