# Generated by Django 3.1.3 on 2021-02-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0016_auto_20210201_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unesco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precision', models.CharField(max_length=200, null=True)),
                ('pays', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='city',
        ),
    ]
