# Generated by Django 3.1.3 on 2021-02-01 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0019_auto_20210201_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='main_function',
            new_name='fonction',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='secondary_function',
            new_name='fonction_secondaire',
        ),
    ]
