# Generated by Django 3.1.3 on 2021-02-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0020_auto_20210201_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='address',
            new_name='adresse',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='complement_address',
            new_name='complement_adresse',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='name',
            new_name='nom',
        ),
    ]
