# Generated by Django 3.1.3 on 2021-02-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0021_auto_20210201_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipement',
            old_name='library',
            new_name='librairie',
        ),
    ]
