# Generated by Django 3.1.3 on 2021-02-01 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0022_auto_20210201_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='labels',
        ),
    ]
