# Generated by Django 3.1.3 on 2021-02-01 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0023_remove_equipement_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement_Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.equipement')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipements.label')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='labels',
            field=models.ManyToManyField(through='equipements.Equipement_Label', to='equipements.Label'),
        ),
    ]
