# Generated by Django 3.1.3 on 2021-02-01 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0024_auto_20210201_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='cinema',
        ),
    ]
