# Generated by Django 3.1.3 on 2021-02-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0025_remove_equipement_cinema'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cinema',
        ),
    ]
