# Generated by Django 3.1.3 on 2021-02-01 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0026_delete_cinema'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('equipement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equipements.equipement')),
                ('cinema_type', models.CharField(max_length=10, null=True)),
                ('number_chairs', models.IntegerField(null=True)),
                ('number_rooms', models.IntegerField(null=True)),
                ('rooms_3d', models.BooleanField(null=True)),
            ],
        ),
    ]
