# Generated by Django 3.1.3 on 2021-02-01 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0027_cinema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='bibliotheque',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='librairie',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='mh',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='unesco',
        ),
    ]
