# Generated by Django 3.1.3 on 2021-02-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0030_architecture_bibliotheque_library_monument_historique_unesco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Library',
            new_name='Librairie',
        ),
    ]
