# Generated by Django 3.1.3 on 2021-03-26 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0031_auto_20210201_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement_type',
            name='domaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.domaine'),
        ),
    ]
