# Generated by Django 3.1.3 on 2021-03-31 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0033_domaineatlas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipement_Type',
            new_name='EquipementType',
        ),
    ]
