# Generated by Django 3.1.3 on 2021-03-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0026_depensesregion_annee'),
        ('equipements', '0034_auto_20210331_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipement_Commune',
            new_name='EquipementCommune',
        ),
    ]
