# Generated by Django 3.1.3 on 2021-03-31 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0035_auto_20210331_1338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipement_Label',
            new_name='EquipementLabel',
        ),
    ]
