# Generated by Django 3.1.3 on 2021-03-31 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0036_auto_20210331_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monument_Historique',
            new_name='MonumentHistorique',
        ),
    ]
