# Generated by Django 3.1.3 on 2021-03-31 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0037_auto_20210331_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypologieLieux',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domaine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.domaineatlas')),
            ],
        ),
    ]
