# Generated by Django 3.1.3 on 2021-06-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0039_detaillieux'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipementtype',
            options={'ordering': ('name',)},
        ),
    ]
