# Generated by Django 3.1.3 on 2021-08-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0040_auto_20210615_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=1000)),
                ('millesime', models.CharField(max_length=4)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.source')),
                ('variable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.equipementtype')),
            ],
        ),
    ]
