# Generated by Django 3.1.3 on 2021-08-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0044_auto_20210817_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipementtype',
            old_name='millesime',
            new_name='year',
        ),
    ]
