# Generated by Django 3.1.3 on 2021-08-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0045_auto_20210817_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metadata',
        ),
    ]
