# Generated by Django 3.1.3 on 2021-09-17 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0047_sousdomaine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='sous_domaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_domaine', to='equipements.sousdomaine'),
        ),
    ]
