# Generated by Django 3.1.3 on 2021-09-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0048_auto_20210917_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipementtype',
            name='sous_domaine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.sousdomaine'),
        ),
    ]
