# Generated by Django 3.1.3 on 2021-09-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0049_equipementtype_sous_domaine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipement',
            name='domaine',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='sous_domaine',
        ),
    ]
