# Generated by Django 3.1.3 on 2021-09-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0050_auto_20210917_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipementtype',
            name='sous_domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipements.sousdomaine'),
        ),
    ]
