# Generated by Django 3.1.3 on 2021-10-06 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipements', '0051_auto_20210929_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sousdomaine',
            options={'ordering': ['name']},
        ),
    ]
