# Generated by Django 3.1.3 on 2021-08-10 13:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admindivisions', '0049_auto_20210809_1347'),
        ('subscribers', '0004_auto_20201214_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('introduction', models.TextField()),
                ('contexte', models.TextField()),
                ('culture', models.TextField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindivisions.region')),
            ],
        ),
    ]
