# Generated by Django 3.1.3 on 2021-09-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0006_auto_20210810_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portrait',
            old_name='contexte',
            new_name='geographie',
        ),
    ]
