# Generated by Django 3.1.3 on 2021-09-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0007_auto_20210915_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='demographie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='economie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='niveaudevie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='qualitedevie',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='travail',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='culture',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='geographie',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
