# Generated by Django 3.1.3 on 2021-09-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0008_auto_20210915_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portrait',
            old_name='culture',
            new_name='offreculturelle',
        ),
    ]
