# Generated by Django 3.1.3 on 2021-09-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0009_auto_20210915_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='depenses',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='emploi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='portrait',
            name='entreprise',
            field=models.TextField(null=True),
        ),
    ]
