# Generated by Django 3.1.3 on 2021-09-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0010_auto_20210915_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portrait',
            old_name='offreculturelle',
            new_name='offre',
        ),
    ]
