# Generated by Django 3.1.3 on 2021-09-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0011_auto_20210915_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portrait',
            old_name='chiffres_cle',
            new_name='donneescontexte',
        ),
    ]
