# Generated by Django 3.1.3 on 2021-09-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0012_auto_20210915_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='donneesculturelles',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
